[build]
  command = "cd frontend && yarn build"
  publish = "frontend/build"

[build.environment]
  YARN_VERSION = "1.22.22"
  NPM_FLAGS = "--force"
  PATH = "$PATH:$(pwd)/frontend/node_modules/.bin"
