# DigitalOcean App Platform configuration
name: shopyy-backend
region: nyc

services:
  - name: api
    github:
      repo: your-username/shopyy-repo
      branch: main
      deploy_on_push: true
    
    source_dir: /backend
    
    build_command: pip install -r requirements.txt
    run_command: uvicorn server:app --host 0.0.0.0 --port 8080
    
    environment_slug: python
    
    instance_count: 1
    instance_size_slug: basic-xxs  # $4/month
    
    routes:
      - path: /
    
    health_check:
      http_path: /docs
    
    envs:
      - key: PORT
        value: "8080"
      - key: DB_NAME
        value: "ecommerce_db"
      - key: MONGO_URL
        scope: RUN_TIME
        type: SECRET
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: STRIPE_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: CORS_ORIGINS
        value: "*"

# Optional: Add MongoDB database
# databases:
#   - name: mongodb
#     engine: MONGODB
#     production: false
