# Fly.io configuration for FastAPI backend
app = "shopyy-backend"
primary_region = "iad"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

# Environment variables (set secrets via: fly secrets set KEY=value)
[env]
  PORT = "8000"
  DB_NAME = "ecommerce_db"

# Set these secrets via CLI:
# fly secrets set MONGO_URL="your-mongodb-url"
# fly secrets set JWT_SECRET="your-secret"
# fly secrets set STRIPE_SECRET_KEY="your-key"
# fly secrets set CORS_ORIGINS="https://your-frontend.netlify.app"
